### ISSUE TITLE
Prototype work flow

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#12]
- Define navigation between screens
- Discussion about features and icon on each screen.
- Build-up flowchart

**Comment by nazimali110** [comment]
- [ ] me do something

- [ ] @sehrishkhawaja  do something

**Comment by sehrishkhawaja** [comment]
[grads questions.docx](https://github.com/nazimali110/GroceryShoppers/files/172729/grads.questions.docx)

**Comment by sehrishkhawaja** [comment]
these the demographic questions which we have asked

**Comment by msmomin** [comment]
![12422271_10154409874277923_1689474470_o](https://cloud.githubusercontent.com/assets/5654236/13759695/24dd7c06-ea0e-11e5-9593-b8157a704b4a.jpg)
