### ISSUE TITLE
Application Name Discussion

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#16]
Provide some app name that you have found

**Comment by sehrishkhawaja** [comment]
I suggest "Fish bank"

**Comment by Ishanmomin** [comment]
I suggest "GroShoppers"

**Comment by rehmanmomin** [comment]
Names like; PreciousSpices, SeaFoodLover, FishPool-OTN

**Comment by msmomin** [comment]
seafood market

**Comment by msmomin** [comment]
FreshFishingMart

**Comment by nazimali110** [comment]
"FiGro" means Fish Grocery.
