### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#17]
Finalize Logo for our app.

**Comment by rehmanmomin** [comment]
It should convey message to the application users` about what we are trying to make for this application.

**Comment by msmomin** [comment]
Application logo should look attractive.

**Comment by rehmanmomin** [comment]
![fishbank-01](https://cloud.githubusercontent.com/assets/17115047/14068232/45f4a9ba-f453-11e5-8682-fdc7110b701b.jpg)

**Comment by rehmanmomin** [comment]
![fishbank-02](https://cloud.githubusercontent.com/assets/17115047/14068236/590db0e6-f453-11e5-8d17-902f19eb1d9a.jpg)

**Comment by Ishanmomin** [comment]
Rehman i like the first one but can change the back ground color and try to give it a sea like background some fishes and sea vectors in the back ground

**Comment by Ishanmomin** [comment]
And try the white logo with blue BG

**Comment by rehmanmomin** [comment]
![fishbank-03](https://cloud.githubusercontent.com/assets/17115047/14090813/e1ac4024-f512-11e5-92e4-f7f72073d348.jpg)
![finalfishbank-02](https://cloud.githubusercontent.com/assets/17115047/14090870/2e7fc272-f513-11e5-8643-85d3d53926e9.png)

**Comment by rehmanmomin** [comment]
Hey guys, i have uploaded better version for the selected logo design. Please let me know, if you need further any changes on a logo design background color.

**Comment by Ishanmomin** [comment]
Now thats what i was looking for I really like the BG for the 2nd one with the sea creatures.. Love it

**Comment by Ishanmomin** [comment]
Lets see what other say about it

**Comment by sehrishkhawaja** [comment]
2nd one is nice

**Comment by msmomin** [comment]
I agree with sehrish or Ishan 2nd  one is perfect.

**Comment by rehmanmomin** [comment]
![aboutusicon-01](https://cloud.githubusercontent.com/assets/17115047/14120313/96fb1ecc-f5c8-11e5-87d0-9757a24eca14.png)
![fishicon-01](https://cloud.githubusercontent.com/assets/17115047/14120310/96f5ee66-f5c8-11e5-9468-ce427557460e.png)
![nutritionicon-01](https://cloud.githubusercontent.com/assets/17115047/14120312/96fab3ec-f5c8-11e5-86bd-235f4a9e65de.png)
![productcomp-01](https://cloud.githubusercontent.com/assets/17115047/14120314/96fbc37c-f5c8-11e5-945d-beaec1896543.png)
![settings-01](https://cloud.githubusercontent.com/assets/17115047/14120311/96f79cde-f5c8-11e5-9897-601d55ceb4ef.png)

**Comment by rehmanmomin** [comment]
Menu Icons used for navigation to different pages.
