### ISSUE TITLE
Making Interview Question for Survey

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#2]

**Comment by Ishanmomin** [comment]
Guyz I am ready with interview questions, let me know when can we sit and discuss that

**Comment by Ishanmomin** [comment]
Sehrish I also need your help in finalizing the survey sheet

**Comment by Ishanmomin** [comment]
![12825595_10154409821017923_1742488663_n](https://cloud.githubusercontent.com/assets/17101376/13757514/a2b5d96c-ea03-11e5-8e20-c5ae6dde19a3.jpg)

**Comment by Ishanmomin** [comment]
I have worked on few question Please let me know if we could add more.
