### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#23]

**Comment by sehrishkhawaja** [comment]
i have completed wireframes

**Comment by sehrishkhawaja** [comment]
![wireframe](https://cloud.githubusercontent.com/assets/17101286/14120169/ff215030-f5c7-11e5-8922-85b9d2bb0ff8.png)

**Comment by Ishanmomin** [comment]
That great now I think the development team can start their work..
