### ISSUE TITLE
Mobile xml desgin

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#25]

**Comment by sehrishkhawaja** [comment]
i have send you a XML so kindly check it.

**Comment by msmomin** [comment]
![screenshot 25](https://cloud.githubusercontent.com/assets/5654236/14223877/b154a36c-f85f-11e5-862b-99c1d87badaa.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/5654236/14223879/b154cb30-f85f-11e5-8459-f9545d467278.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/5654236/14223880/b1550ef6-f85f-11e5-8cbf-9ae56ecb541d.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/5654236/14223881/b1553ba6-f85f-11e5-9404-f1d1b31a9057.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/5654236/14223882/b156a72a-f85f-11e5-880f-263b015d2b7f.png)
![screenshot 30](https://cloud.githubusercontent.com/assets/5654236/14223878/b154ca86-f85f-11e5-9af8-3d949e71c88b.png)
![screenshot 31](https://cloud.githubusercontent.com/assets/5654236/14223885/b1609622-f85f-11e5-9b37-8ef7e88f10f0.png)
![screenshot 32](https://cloud.githubusercontent.com/assets/5654236/14223883/b15fe682-f85f-11e5-84c7-dbc0dceac118.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/5654236/14223884/b1602e6c-f85f-11e5-9845-126522e1eb41.png)
![screenshot 34](https://cloud.githubusercontent.com/assets/5654236/14223886/b160ea96-f85f-11e5-9e30-0848557ddb0e.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/5654236/14223887/b1614d42-f85f-11e5-846c-ca5034ab8248.png)
![screenshot 21](https://cloud.githubusercontent.com/assets/5654236/14223888/b1625606-f85f-11e5-8156-b61f1238b733.png)
![screenshot 22](https://cloud.githubusercontent.com/assets/5654236/14223890/b16a5928-f85f-11e5-8b52-779401c0e68e.png)
![screenshot 23](https://cloud.githubusercontent.com/assets/5654236/14223889/b16a2138-f85f-11e5-87f7-15120b7cf31d.png)
![screenshot 24](https://cloud.githubusercontent.com/assets/5654236/14223891/b16b29ac-f85f-11e5-821a-89c38270b772.png)

**Comment by msmomin** [comment]
these are the screen shots of application

**Comment by msmomin** [comment]
me and nazim will provide zip file of actual code

**Comment by msmomin** [comment]
sehrish please add nutrition XML

**Comment by sehrishkhawaja** [comment]
![12921896_1295685597112191_70763707_o](https://cloud.githubusercontent.com/assets/17101286/14223908/3936ac08-f860-11e5-87d6-3edb5e28a548.png)
![12919515_1295685633778854_119439823_o](https://cloud.githubusercontent.com/assets/17101286/14223910/3ae55392-f860-11e5-9fe5-206739c9b77a.png)

**Comment by sehrishkhawaja** [comment]
Mohsin these are the screen shots of the XML which we have created together in your laptop. are they ok?

**Comment by msmomin** [comment]
do you need any changes in this XML?
