### ISSUE TITLE
Building Application

### ISSUE THREAD

**Issue by nazimali110** [nazimali110/GroceryShoppers#5]

**Comment by nazimali110** [comment]
I and @msmomin are working on Andriod application

**Comment by nazimali110** [comment]
@msmomin need help for making code

**Comment by msmomin** [comment]
Nazim i have uploaded XML files. check them and tell me if you need any changes.

**Comment by msmomin** [comment]
tell me where you need help? i will help you to do that?

**Comment by nazimali110** [comment]
You remember the call and we fix some error. And I also add Nutrition features in which we can see fish related to nutrition.
